-- Your SQL goes here
CREATE TABLE app_user (
	 id INT PRIMARY KEY,
  login VARCHAR(255) NOT NULL,
  avatar VARCHAR(255) NOT NULL,
  password BYTEA NULL,
  status VARCHAR(255) NOT NULL DEFAULT 'online',
  wins INTEGER NOT NULL DEFAULT 0, 
  losses INTEGER NOT NULL DEFAULT 0
);