version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rust_server
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - ./development:/usr/src/development
  postgres:
    image: postgres
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - 5432:5432
