[package]
name = "http-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0.0"
diesel = { version = "1.4.7", features = ["postgres", "r2d2", "chrono"] }
diesel_migrations = "1"
dotenvy = "0.15"
lazy_static = "1.4.0"