[package]
name = "http-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0.0"
diesel = { version = "2.0", features = ["postgres", "r2d2", "chrono"] }
diesel_migrations = "2.0"
dotenvy = "0.15"
anyhow = "1.0.72"