version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres_db
    networks:
      - inception_network
    env_file:
      - ../source/.env
    ports:
      - 5432:5432

  your_app:
      build: .
      container_name: dev
      env_file:
        - ../source/.env
      ports:
        - "4242:4242"
        - "8080:8080"
      volumes:
        - ./source:/usr/src
      networks:
        - inception_network

networks:
  inception_network:  # Define the network here
    driver: bridge 